use std::path::Path;

pub fn write_f32_csv(
    path: impl AsRef<Path>,
    keys: Vec<String>,
    valss: Vec<Vec<f32>>,
    header: &str,
) -> std::io::Result<()> {
    assert_eq!(keys.len(), valss.len());
    let len = valss[0].len();
    for vals in valss.iter() {
        assert_eq!(len, vals.len())
    }
    let mut string = header.to_string();
    string.push_str("\n\n");

    for s in keys {
        string.push_str(&format!("{}, ", s))
    }
    string.push_str("\n\n");

    for i in 0..len {
        for vals in valss.iter() {
            string.push_str(&format!("{:e}, ", vals[i]))
        }
        string.push('\n')
    }
    std::fs::write(path, string)
}

pub fn make_csv_header(comment: &str) -> String {
    let mut header = comment.to_string();
    header.push_str(
        "\nThis file was generated by Speckmeter\nhttps://github.com/messiamax/speckmeter",
    );
    header.push_str(&format!(
        "\n{}\n",
        chrono::Local::now().format("%Y %m.%d. %H:%M:%S")
    ));
    header
}
